/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PrimeiroAcessoRouteImport } from './routes/primeiro-acesso'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as AuthenticatedAdminAutomationRouteImport } from './routes/_authenticated/admin/automation'
import { Route as AuthenticatedAdminBillingRouteImport } from './routes/_authenticated/admin/billing'
import { Route as AuthenticatedAdminContractsRouteImport } from './routes/_authenticated/admin/contracts'
import { Route as AuthenticatedAdminDiagnosticsRouteImport } from './routes/_authenticated/admin/diagnostics'
import { Route as AuthenticatedAdminExportsRouteImport } from './routes/_authenticated/admin/exports'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin/import'
import { Route as AuthenticatedAdminIndustriesRouteImport } from './routes/_authenticated/admin/industries'
import { Route as AuthenticatedAdminOccurrencesRouteImport } from './routes/_authenticated/admin/occurrences'
import { Route as AuthenticatedAdminPromotersRouteImport } from './routes/_authenticated/admin/promoters'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminRoutesRouteImport } from './routes/_authenticated/admin/routes'
import { Route as AuthenticatedAdminRoutes_newRouteImport } from './routes/_authenticated/admin/routes_new'
import { Route as AuthenticatedAdminStoresRouteImport } from './routes/_authenticated/admin/stores'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminVisitsRouteImport } from './routes/_authenticated/admin/visits'
import { Route as AuthenticatedAdminVisualizarPromotorRouteImport } from './routes/_authenticated/admin/visualizar-promotor'
import { Route as AuthenticatedIndustryIndexRouteImport } from './routes/_authenticated/industry/index'
import { Route as AuthenticatedIndustryBillingRouteImport } from './routes/_authenticated/industry/billing'
import { Route as AuthenticatedIndustryExportsRouteImport } from './routes/_authenticated/industry/exports'
import { Route as AuthenticatedPromoterIndexRouteImport } from './routes/_authenticated/promoter/index'
import { Route as ApiPublicWebhookRouteImport } from './routes/api/public/webhook'
import { Route as ApiReportsPdfRouteImport } from './routes/api/reports.pdf'
import { Route as AuthenticatedPromoterVisitVisitIdRouteImport } from './routes/_authenticated/promoter/visit.$visitId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimeiroAcessoRoute = PrimeiroAcessoRouteImport.update({
  id: '/primeiro-acesso',
  path: '/primeiro-acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAutomationRoute =
  AuthenticatedAdminAutomationRouteImport.update({
    id: '/automation',
    path: '/automation',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBillingRoute =
  AuthenticatedAdminBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminContractsRoute =
  AuthenticatedAdminContractsRouteImport.update({
    id: '/contracts',
    path: '/contracts',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDiagnosticsRoute =
  AuthenticatedAdminDiagnosticsRouteImport.update({
    id: '/diagnostics',
    path: '/diagnostics',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminExportsRoute =
  AuthenticatedAdminExportsRouteImport.update({
    id: '/exports',
    path: '/exports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminIndustriesRoute =
  AuthenticatedAdminIndustriesRouteImport.update({
    id: '/industries',
    path: '/industries',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOccurrencesRoute =
  AuthenticatedAdminOccurrencesRouteImport.update({
    id: '/occurrences',
    path: '/occurrences',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPromotersRoute =
  AuthenticatedAdminPromotersRouteImport.update({
    id: '/promoters',
    path: '/promoters',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRoutesRoute =
  AuthenticatedAdminRoutesRouteImport.update({
    id: '/routes',
    path: '/routes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRoutes_newRoute =
  AuthenticatedAdminRoutes_newRouteImport.update({
    id: '/routes_new',
    path: '/routes_new',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStoresRoute =
  AuthenticatedAdminStoresRouteImport.update({
    id: '/stores',
    path: '/stores',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminVisitsRoute =
  AuthenticatedAdminVisitsRouteImport.update({
    id: '/visits',
    path: '/visits',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminVisualizarPromotorRoute =
  AuthenticatedAdminVisualizarPromotorRouteImport.update({
    id: '/visualizar-promotor',
    path: '/visualizar-promotor',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedIndustryIndexRoute =
  AuthenticatedIndustryIndexRouteImport.update({
    id: '/industry/',
    path: '/industry/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIndustryBillingRoute =
  AuthenticatedIndustryBillingRouteImport.update({
    id: '/industry/billing',
    path: '/industry/billing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIndustryExportsRoute =
  AuthenticatedIndustryExportsRouteImport.update({
    id: '/industry/exports',
    path: '/industry/exports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPromoterIndexRoute =
  AuthenticatedPromoterIndexRouteImport.update({
    id: '/promoter/',
    path: '/promoter/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWebhookRoute = ApiPublicWebhookRouteImport.update({
  id: '/api/public/webhook',
  path: '/api/public/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsPdfRoute = ApiReportsPdfRouteImport.update({
  id: '/api/reports/pdf',
  path: '/api/reports/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPromoterVisitVisitIdRoute =
  AuthenticatedPromoterVisitVisitIdRouteImport.update({
    id: '/promoter/visit/$visitId',
    path: '/promoter/visit/$visitId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/automation': typeof AuthenticatedAdminAutomationRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/contracts': typeof AuthenticatedAdminContractsRoute
  '/admin/diagnostics': typeof AuthenticatedAdminDiagnosticsRoute
  '/admin/exports': typeof AuthenticatedAdminExportsRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/industries': typeof AuthenticatedAdminIndustriesRoute
  '/admin/occurrences': typeof AuthenticatedAdminOccurrencesRoute
  '/admin/promoters': typeof AuthenticatedAdminPromotersRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/routes': typeof AuthenticatedAdminRoutesRoute
  '/admin/routes_new': typeof AuthenticatedAdminRoutes_newRoute
  '/admin/stores': typeof AuthenticatedAdminStoresRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/visits': typeof AuthenticatedAdminVisitsRoute
  '/admin/visualizar-promotor': typeof AuthenticatedAdminVisualizarPromotorRoute
  '/industry/billing': typeof AuthenticatedIndustryBillingRoute
  '/industry/exports': typeof AuthenticatedIndustryExportsRoute
  '/api/public/webhook': typeof ApiPublicWebhookRoute
  '/api/reports/pdf': typeof ApiReportsPdfRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/industry/': typeof AuthenticatedIndustryIndexRoute
  '/promoter/': typeof AuthenticatedPromoterIndexRoute
  '/promoter/visit/$visitId': typeof AuthenticatedPromoterVisitVisitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/automation': typeof AuthenticatedAdminAutomationRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/contracts': typeof AuthenticatedAdminContractsRoute
  '/admin/diagnostics': typeof AuthenticatedAdminDiagnosticsRoute
  '/admin/exports': typeof AuthenticatedAdminExportsRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/industries': typeof AuthenticatedAdminIndustriesRoute
  '/admin/occurrences': typeof AuthenticatedAdminOccurrencesRoute
  '/admin/promoters': typeof AuthenticatedAdminPromotersRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/routes': typeof AuthenticatedAdminRoutesRoute
  '/admin/routes_new': typeof AuthenticatedAdminRoutes_newRoute
  '/admin/stores': typeof AuthenticatedAdminStoresRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/visits': typeof AuthenticatedAdminVisitsRoute
  '/admin/visualizar-promotor': typeof AuthenticatedAdminVisualizarPromotorRoute
  '/industry/billing': typeof AuthenticatedIndustryBillingRoute
  '/industry/exports': typeof AuthenticatedIndustryExportsRoute
  '/api/public/webhook': typeof ApiPublicWebhookRoute
  '/api/reports/pdf': typeof ApiReportsPdfRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/industry': typeof AuthenticatedIndustryIndexRoute
  '/promoter': typeof AuthenticatedPromoterIndexRoute
  '/promoter/visit/$visitId': typeof AuthenticatedPromoterVisitVisitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/automation': typeof AuthenticatedAdminAutomationRoute
  '/_authenticated/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/_authenticated/admin/contracts': typeof AuthenticatedAdminContractsRoute
  '/_authenticated/admin/diagnostics': typeof AuthenticatedAdminDiagnosticsRoute
  '/_authenticated/admin/exports': typeof AuthenticatedAdminExportsRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/admin/industries': typeof AuthenticatedAdminIndustriesRoute
  '/_authenticated/admin/occurrences': typeof AuthenticatedAdminOccurrencesRoute
  '/_authenticated/admin/promoters': typeof AuthenticatedAdminPromotersRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/routes': typeof AuthenticatedAdminRoutesRoute
  '/_authenticated/admin/routes_new': typeof AuthenticatedAdminRoutes_newRoute
  '/_authenticated/admin/stores': typeof AuthenticatedAdminStoresRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/visits': typeof AuthenticatedAdminVisitsRoute
  '/_authenticated/admin/visualizar-promotor': typeof AuthenticatedAdminVisualizarPromotorRoute
  '/_authenticated/industry/billing': typeof AuthenticatedIndustryBillingRoute
  '/_authenticated/industry/exports': typeof AuthenticatedIndustryExportsRoute
  '/api/public/webhook': typeof ApiPublicWebhookRoute
  '/api/reports/pdf': typeof ApiReportsPdfRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/industry/': typeof AuthenticatedIndustryIndexRoute
  '/_authenticated/promoter/': typeof AuthenticatedPromoterIndexRoute
  '/_authenticated/promoter/visit/$visitId': typeof AuthenticatedPromoterVisitVisitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/primeiro-acesso'
    | '/admin'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/admin/audit'
    | '/admin/automation'
    | '/admin/billing'
    | '/admin/contracts'
    | '/admin/diagnostics'
    | '/admin/exports'
    | '/admin/import'
    | '/admin/industries'
    | '/admin/occurrences'
    | '/admin/promoters'
    | '/admin/reports'
    | '/admin/routes'
    | '/admin/routes_new'
    | '/admin/stores'
    | '/admin/users'
    | '/admin/visits'
    | '/admin/visualizar-promotor'
    | '/industry/billing'
    | '/industry/exports'
    | '/api/public/webhook'
    | '/api/reports/pdf'
    | '/admin/'
    | '/industry/'
    | '/promoter/'
    | '/promoter/visit/$visitId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/primeiro-acesso'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/admin/audit'
    | '/admin/automation'
    | '/admin/billing'
    | '/admin/contracts'
    | '/admin/diagnostics'
    | '/admin/exports'
    | '/admin/import'
    | '/admin/industries'
    | '/admin/occurrences'
    | '/admin/promoters'
    | '/admin/reports'
    | '/admin/routes'
    | '/admin/routes_new'
    | '/admin/stores'
    | '/admin/users'
    | '/admin/visits'
    | '/admin/visualizar-promotor'
    | '/industry/billing'
    | '/industry/exports'
    | '/api/public/webhook'
    | '/api/reports/pdf'
    | '/admin'
    | '/industry'
    | '/promoter'
    | '/promoter/visit/$visitId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/primeiro-acesso'
    | '/_authenticated/admin'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/automation'
    | '/_authenticated/admin/billing'
    | '/_authenticated/admin/contracts'
    | '/_authenticated/admin/diagnostics'
    | '/_authenticated/admin/exports'
    | '/_authenticated/admin/import'
    | '/_authenticated/admin/industries'
    | '/_authenticated/admin/occurrences'
    | '/_authenticated/admin/promoters'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/routes'
    | '/_authenticated/admin/routes_new'
    | '/_authenticated/admin/stores'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/visits'
    | '/_authenticated/admin/visualizar-promotor'
    | '/_authenticated/industry/billing'
    | '/_authenticated/industry/exports'
    | '/api/public/webhook'
    | '/api/reports/pdf'
    | '/_authenticated/admin/'
    | '/_authenticated/industry/'
    | '/_authenticated/promoter/'
    | '/_authenticated/promoter/visit/$visitId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PrimeiroAcessoRoute: typeof PrimeiroAcessoRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  ApiPublicWebhookRoute: typeof ApiPublicWebhookRoute
  ApiReportsPdfRoute: typeof ApiReportsPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primeiro-acesso': {
      id: '/primeiro-acesso'
      path: '/primeiro-acesso'
      fullPath: '/primeiro-acesso'
      preLoaderRoute: typeof PrimeiroAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/automation': {
      id: '/_authenticated/admin/automation'
      path: '/automation'
      fullPath: '/admin/automation'
      preLoaderRoute: typeof AuthenticatedAdminAutomationRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/billing': {
      id: '/_authenticated/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AuthenticatedAdminBillingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/contracts': {
      id: '/_authenticated/admin/contracts'
      path: '/contracts'
      fullPath: '/admin/contracts'
      preLoaderRoute: typeof AuthenticatedAdminContractsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/diagnostics': {
      id: '/_authenticated/admin/diagnostics'
      path: '/diagnostics'
      fullPath: '/admin/diagnostics'
      preLoaderRoute: typeof AuthenticatedAdminDiagnosticsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/exports': {
      id: '/_authenticated/admin/exports'
      path: '/exports'
      fullPath: '/admin/exports'
      preLoaderRoute: typeof AuthenticatedAdminExportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/industries': {
      id: '/_authenticated/admin/industries'
      path: '/industries'
      fullPath: '/admin/industries'
      preLoaderRoute: typeof AuthenticatedAdminIndustriesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/occurrences': {
      id: '/_authenticated/admin/occurrences'
      path: '/occurrences'
      fullPath: '/admin/occurrences'
      preLoaderRoute: typeof AuthenticatedAdminOccurrencesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/promoters': {
      id: '/_authenticated/admin/promoters'
      path: '/promoters'
      fullPath: '/admin/promoters'
      preLoaderRoute: typeof AuthenticatedAdminPromotersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/routes': {
      id: '/_authenticated/admin/routes'
      path: '/routes'
      fullPath: '/admin/routes'
      preLoaderRoute: typeof AuthenticatedAdminRoutesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/routes_new': {
      id: '/_authenticated/admin/routes_new'
      path: '/routes_new'
      fullPath: '/admin/routes_new'
      preLoaderRoute: typeof AuthenticatedAdminRoutes_newRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/stores': {
      id: '/_authenticated/admin/stores'
      path: '/stores'
      fullPath: '/admin/stores'
      preLoaderRoute: typeof AuthenticatedAdminStoresRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/visits': {
      id: '/_authenticated/admin/visits'
      path: '/visits'
      fullPath: '/admin/visits'
      preLoaderRoute: typeof AuthenticatedAdminVisitsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/visualizar-promotor': {
      id: '/_authenticated/admin/visualizar-promotor'
      path: '/visualizar-promotor'
      fullPath: '/admin/visualizar-promotor'
      preLoaderRoute: typeof AuthenticatedAdminVisualizarPromotorRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/industry/': {
      id: '/_authenticated/industry/'
      path: '/industry'
      fullPath: '/industry/'
      preLoaderRoute: typeof AuthenticatedIndustryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/industry/billing': {
      id: '/_authenticated/industry/billing'
      path: '/industry/billing'
      fullPath: '/industry/billing'
      preLoaderRoute: typeof AuthenticatedIndustryBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/industry/exports': {
      id: '/_authenticated/industry/exports'
      path: '/industry/exports'
      fullPath: '/industry/exports'
      preLoaderRoute: typeof AuthenticatedIndustryExportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/promoter/': {
      id: '/_authenticated/promoter/'
      path: '/promoter'
      fullPath: '/promoter/'
      preLoaderRoute: typeof AuthenticatedPromoterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhook': {
      id: '/api/public/webhook'
      path: '/api/public/webhook'
      fullPath: '/api/public/webhook'
      preLoaderRoute: typeof ApiPublicWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports/pdf': {
      id: '/api/reports/pdf'
      path: '/api/reports/pdf'
      fullPath: '/api/reports/pdf'
      preLoaderRoute: typeof ApiReportsPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/promoter/visit/$visitId': {
      id: '/_authenticated/promoter/visit/$visitId'
      path: '/promoter/visit/$visitId'
      fullPath: '/promoter/visit/$visitId'
      preLoaderRoute: typeof AuthenticatedPromoterVisitVisitIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminAutomationRoute: typeof AuthenticatedAdminAutomationRoute
  AuthenticatedAdminBillingRoute: typeof AuthenticatedAdminBillingRoute
  AuthenticatedAdminContractsRoute: typeof AuthenticatedAdminContractsRoute
  AuthenticatedAdminDiagnosticsRoute: typeof AuthenticatedAdminDiagnosticsRoute
  AuthenticatedAdminExportsRoute: typeof AuthenticatedAdminExportsRoute
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminIndustriesRoute: typeof AuthenticatedAdminIndustriesRoute
  AuthenticatedAdminOccurrencesRoute: typeof AuthenticatedAdminOccurrencesRoute
  AuthenticatedAdminPromotersRoute: typeof AuthenticatedAdminPromotersRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminRoutesRoute: typeof AuthenticatedAdminRoutesRoute
  AuthenticatedAdminRoutes_newRoute: typeof AuthenticatedAdminRoutes_newRoute
  AuthenticatedAdminStoresRoute: typeof AuthenticatedAdminStoresRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminVisitsRoute: typeof AuthenticatedAdminVisitsRoute
  AuthenticatedAdminVisualizarPromotorRoute: typeof AuthenticatedAdminVisualizarPromotorRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
    AuthenticatedAdminAutomationRoute: AuthenticatedAdminAutomationRoute,
    AuthenticatedAdminBillingRoute: AuthenticatedAdminBillingRoute,
    AuthenticatedAdminContractsRoute: AuthenticatedAdminContractsRoute,
    AuthenticatedAdminDiagnosticsRoute: AuthenticatedAdminDiagnosticsRoute,
    AuthenticatedAdminExportsRoute: AuthenticatedAdminExportsRoute,
    AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
    AuthenticatedAdminIndustriesRoute: AuthenticatedAdminIndustriesRoute,
    AuthenticatedAdminOccurrencesRoute: AuthenticatedAdminOccurrencesRoute,
    AuthenticatedAdminPromotersRoute: AuthenticatedAdminPromotersRoute,
    AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
    AuthenticatedAdminRoutesRoute: AuthenticatedAdminRoutesRoute,
    AuthenticatedAdminRoutes_newRoute: AuthenticatedAdminRoutes_newRoute,
    AuthenticatedAdminStoresRoute: AuthenticatedAdminStoresRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminVisitsRoute: AuthenticatedAdminVisitsRoute,
    AuthenticatedAdminVisualizarPromotorRoute:
      AuthenticatedAdminVisualizarPromotorRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedIndustryBillingRoute: typeof AuthenticatedIndustryBillingRoute
  AuthenticatedIndustryExportsRoute: typeof AuthenticatedIndustryExportsRoute
  AuthenticatedIndustryIndexRoute: typeof AuthenticatedIndustryIndexRoute
  AuthenticatedPromoterIndexRoute: typeof AuthenticatedPromoterIndexRoute
  AuthenticatedPromoterVisitVisitIdRoute: typeof AuthenticatedPromoterVisitVisitIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedIndustryBillingRoute: AuthenticatedIndustryBillingRoute,
  AuthenticatedIndustryExportsRoute: AuthenticatedIndustryExportsRoute,
  AuthenticatedIndustryIndexRoute: AuthenticatedIndustryIndexRoute,
  AuthenticatedPromoterIndexRoute: AuthenticatedPromoterIndexRoute,
  AuthenticatedPromoterVisitVisitIdRoute:
    AuthenticatedPromoterVisitVisitIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PrimeiroAcessoRoute: PrimeiroAcessoRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  ApiPublicWebhookRoute: ApiPublicWebhookRoute,
  ApiReportsPdfRoute: ApiReportsPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
